stages:
  - build
  - test
  - scan
  - notify

variables:
  PROJECT_NAME: "linkedin-gitlab-cicd"

# Build stage
build-job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building the project - Docker Image..."
    - docker build -t $PROJECT_NAME:$CI_PIPELINE_IID .


# Test stage - Validate dependencies
npm-test:
  stage: test
  image: node:16
  needs: [build-job]
  script:
    - echo "Installing and validating backend dependencies..."
    - cd backend
    - npm install
    - echo "Installing and validating frontend dependencies..."
    - cd ../frontend
    - npm install
    - echo "All dependencies validated successfully"

# Security scan stage - Trivy vulnerability scan
trivy-scan:
  stage: scan
  image: docker:24
  services:
    - docker:dind
  needs: [build-job]
  script:
    - echo "Running Trivy security scan..."
    - docker build -t $PROJECT_NAME:$CI_PIPELINE_IID .
    - apk add --no-cache curl    
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
    - trivy image --severity HIGH,CRITICAL --ignore-unfixed --format json --output trivy-report.json $PROJECT_NAME:$CI_PIPELINE_IID
    - echo "Trivy scan complete"

  artifacts:
    paths:
      - trivy-report.json
    expire_in: 7 days

notify-on-failure:
  stage: notify
  script:
    - echo "🚨 Build or Test job failed for ${PROJECT_NAME}! Please check logs."
  when: on_failure