stages:
  - build
  - test
  - scan
  - notify
  - push

  
variables:
  PROJECT_NAME: "linkedin-gitlab-cicd"

# Build stage
build-job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building the project - Docker Image..."
    - docker build -t $PROJECT_NAME:$CI_PIPELINE_IID .


# Test stage - Validate dependencies
npm-test:
  stage: test
  image: node:16
  needs: [build-job]
  script:
    - echo "Installing and validating backend dependencies..."
    - cd backend
    - npm install
    - echo "Installing and validating frontend dependencies..."
    - cd ../frontend
    - npm install
    - echo "All dependencies validated successfully"

# Security scan stage - Trivy vulnerability scan
trivy-scan:
  stage: scan
  image: docker:24
  services:
    - docker:dind
  needs: [build-job]
  script:
    - echo "Running Trivy security scan..."
    - docker build -t $PROJECT_NAME:$CI_PIPELINE_IID .
    - apk add --no-cache curl    
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
    - trivy image --severity HIGH,CRITICAL --ignore-unfixed --format json --output trivy-report.json $PROJECT_NAME:$CI_PIPELINE_IID
    - echo "Trivy scan complete"

  artifacts:
    paths:
      - trivy-report.json
    expire_in: 7 days

notify-on-failure:
  stage: notify
  script:
    - echo "🚨 Build or Test job failed for ${PROJECT_NAME}! Please check logs."
  when: on_failure


# Push Stage - Push to GitLab Container Registry
push-to-registry:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  needs: [trivy-scan]
  script:
    - echo "Logging in to GitLab Container Registry..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "Building and pushing image..."
    - docker build -t $CI_REGISTRY_IMAGE:$CI_PIPELINE_IID .
    - docker tag $CI_REGISTRY_IMAGE:$CI_PIPELINE_IID $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_PIPELINE_IID
    - docker push $CI_REGISTRY_IMAGE:latest
    - echo "Image pushed successfully!"
  only:
    - main

